name: release-published
on:
  release:
    types: [published]
jobs:
  npm:
    name: Publish package to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
          scope: okkema
      - name: Install dependencies
        run: npm ci --omit dev
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  github:
    name: Publish package to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com
      - name: Install dependencies
        run: npm ci --omit dev
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
